YªçŠx-®éÜj×¢ëiºÚ+Š§j[h‘éÜ¢éíãzN‹Z–‹­¦ëeŠw¬Õ¥µÁ½ÉĞìÕÍ•MÑ…Ñ”°ÕÍ•™™•Ğô™É½´€É•…Ğœì)¥µÁ½ÉĞì=ÕÑ±•Ğ°9…Ù1¥¹¬°ÕÍ•9…Ù¥…Ñ”ô™É½´€É•…ĞµÉ½ÕÑ•Èµ‘½´œì)¥µÁ½ÉĞìÕÍ•ÕÑ ô™É½´€œ¸¸½½¹Ñ•áĞ½ÕÑ¡½¹Ñ•áĞœì)¥µÁ½ÉĞìÕÍ•$Äá¸ô™É½´€œ¸¸½½¹Ñ•áĞ½$Äá¹½¹Ñ•áĞœì)¥µÁ½ÉĞM•ÉÙ•ÉMÑ…ÑÕÌ™É½´€œ¸½M•ÉÙ•ÉMÑ…ÑÕÌœì)¥µÁ½ÉĞ±½‰…±M•…É ™É½´€œ¸½±½‰…±M•…É œì)¥µÁ½ÉĞ%½¸™É½´€œ¸½%½¸œì)¥µÁ½ÉĞ1¥•¹Í•	…¹¹•È™É½´€œ¸½1¥•¹Í•	…¹¹•Èœì)¥µÁ½ÉĞÑ½…ÍĞ™É½´€É•…Ğµ¡½ĞµÑ½…ÍĞœì()½¹ÍĞ9Y}MQ%=9L€ôl(€ì(€€€Ñ¬è€¹…Ø¹µ…¥¸œ°(€€€¥Ñ•µÌèl(€€€€€ìÑ¼è€œ½Á½Ìœ°€€€€€€€€€€€€¥½¸è€Á½¥¹Ñ}½™}Í…±”œ°€Ñ¬è€¹…Ø¹Á½Ìœ°€€€€€€€€…±İ…åÌèÑÉÕ”ô°(€€€€€ìÑ¼è€œ½‘…Í¡‰½…Éœ°€€€€€€¥½¸è€‘…Í¡‰½…Éœ°€€€€€€Ñ¬è€¹…Ø¹‘…Í¡‰½…Éœ°€€…‘µ¥¹=¹±äèÑÉÕ”ô°(€€€t(€ô°(€ì(€€€Ñ¬è€¹…Ø¹¥¹Ù•¹Ñ½Éäœ°(€€€¥Ñ•µÌèl(€€€€€ìÑ¼è€œ½ÁÉ½‘ÕÑÌœ°€€€€€€€¥½¸è€¥¹Ù•¹Ñ½Éå|Èœ°€€€€Ñ¬è€¹…Ø¹ÁÉ½‘ÕÑÌœ°€€€…‘µ¥¹=¹±äèÑÉÕ”ô°(€€€€€ìÑ¼è€œ½ÁÉ½‘ÕÑÌ½¥µÁ½ÉĞœ°¥½¸è€ÕÁ±½…‘}™¥±”œ°€€€€Ñ¬è€¹…Ø¹¥µÁ½ÉÑ}ÍØœ°€…‘µ¥¹=¹±äèÑÉÕ”ô°(€€€€€ìÑ¼è€œ½ÍÑ½¬œ°€€€€€€€€€€¥½¸è€Íİ…Á}¡½É¥èœ°€€€€€Ñ¬è€¹…Ø¹ÍÑ½¬œ°€€€€€€…‘µ¥¹=¹±äèÑÉÕ”ô°(€€€€€ìÑ¼è€œ½ÍÕÁÁ±¥•ÉÌœ°€€€€€€¥½¸è€±½…±}Í¡¥ÁÁ¥¹œœ°€Ñ¬è€¹…Ø¹ÍÕÁÁ±¥•ÉÌœ°€€…‘µ¥¹=¹±äèÑÉÕ”ô°(€€€t(€ô°(€ì(€€€Ñ¬è€¹…Ø¹Í…±•Ìœ°(€€€¥Ñ•µÌèl(€€€€€ìÑ¼è€œ½ÑÉ…¹Í…Ñ¥½¹Ìœ°€€€¥½¸è€É••¥ÁÑ}±½¹œœ°€€€Ñ¬è€¹…Ø¹ÑÉ…¹Í…Ñ¥½¹Ìœ±…‘µ¥¹=¹±äèÑÉÕ”ô°($€ìÑ¼è€œ½Í•ÉÙ¥”µ½É‘•ÉÌœ°€¥½¸è€‰Õ¥±œ°€€€€€€€€€€€Ñ¬è€=É‘•ÈM•ÉÙ¥Ìœ°€€€€…±İ…åÌèÑÉÕ”ô°(€€€€€ìÑ¼è€œ½ÕÍÑ½µ•ÉÌœ°€€€€€€¥½¸è€É½ÕÀœ°€€€€€€€€€€Ñ¬è€¹…Ø¹ÕÍÑ½µ•ÉÌœ°€€…‘µ¥¹=¹±äèÑÉÕ”ô°(€€€€€ìÑ¼è€œ½‘¥Í½Õ¹ÑÌœ°€€€€€€¥½¸è€Í•±°œ°€€€ƒ~=êÚ$z{-®éÜj×tainer-low); color: var(--primary); }
        .nav-item--active { background: var(--primary-fixed); color: var(--primary); font-weight: 700; }
        .main-content { flex: 1; margin-left: 248px; min-height: 100dvh; background: var(--surface); }
        .mobile-topbar { display: none; position: fixed; top: 0; left: 0; right: 0; height: 58px; background: color-mix(in srgb, var(--surface-container-lowest) 92%, transparent); backdrop-filter: blur(12px); border-bottom: 1px solid var(--outline-variant); padding: 0 14px; align-items: center; justify-content: space-between; z-index: 25; }
        .drawer-scrim { position: fixed; inset: 0; background: rgba(24,28,32,.4); backdrop-filter: blur(3px); z-index: 40; display: flex; }
        .drawer { width: 286px; height: 100%; background: var(--surface-container-lowest); border-right: 1px solid var(--outline-variant); display: flex; flex-direction: column; box-shadow: var(--shadow-3); animation: slideInLeft .2s cubic-bezier(.34,1.3,.64,1); }
        .drawer-head { display: flex; align-items: center; justify-content: space-between; padding: 14px 12px 10px; border-bottom: 1px solid var(--outline-variant); margin-bottom: 6px; }
        @keyframes slideInLeft { from { transform: translateX(-40px); opacity: 0 } to { transform: translateX(0); opacity: 1 } }
        @media (max-width: 768px) { .sidebar { display: none; } .mobile-topbar { display: flex; } .main-content { margin-left: 0; padding-top: 58px; } }
      `}</style>
    </div>
  );
}
