YªçŠx-®éÜj×¢ëiºÚ+Š§j[h‘éÜ¢éíß9N‹Z–‹­¦ëeŠw¬Õ¥µÁ½ÉĞìÕÍ•MÑ…Ñ”ô™É½´€É•…Ğœì)¥µÁ½ÉĞìÕÍ•9…Ù¥…Ñ”ô™É½´€É•…ĞµÉ½ÕÑ•Èµ‘½´œì)¥µÁ½ÉĞÑ½…ÍĞ™É½´€É•…Ğµ¡½ĞµÑ½…ÍĞœì)¥µÁ½ÉĞìÕÍ•ÕÑ ô™É½´€œ¸¸½½¹Ñ•áĞ½ÕÑ¡½¹Ñ•áĞœì)¥µÁ½ÉĞìÕÍ•$Äá¸ô™É½´€œ¸¸½½¹Ñ•áĞ½$Äá¹½¹Ñ•áĞœì)¥µÁ½ÉĞ%½¸™É½´€œ¸¸½½µÁ½¹•¹ÑÌ½%½¸œì)¥µÁ½ÉĞì•Ñ!½µ•A…Ñ ô™É½´€œ¸¸½ÕÑ¥±Ì½¹…Ù¥…Ñ¥½¸¹µ©Ìœì()½¹ÍĞ	9%QL€ôl(€lÁ½¥¹Ñ}½™}Í…±”œ°€QÉ…¹Í…­Í¤•Á…ĞÕ¹ÑÕ¬­…Í¥Èt°(€l¥¹Ù•¹Ñ½Éå|Èœ°€MÑ½¬°¡…É„°‘…¸±…Á½É…¸Ñ•É­•¹‘…±¤t°(€l‰Õ¥±œ°€)…Í„€˜ÍÁ…É•Á…ÉĞ‘…±…´Í…ÑÔ¹½Ñ„t°(€lİ¥™¥}½™˜œ°€Q•Ñ…À‰•­•É©„Ñ…¹Á„¥¹Ñ•É¹•Ğt°)tì()•áÁ½ÉĞ‘•™…Õ±Ğ™Õ¹Ñ¥½¸1½¥¸ ¤ì(€½¹ÍĞì±½¥¸ô€ôÕÍ•ÕÑ  ¤ì(€½¹ÍĞìĞ°Ñ½±•1…¹œ°Ñ½±•Q¡•µ”°¥Í…É¬ô€ôÕÍ•$Äá¸ ¤ì(€½¹ÍĞ¹…Ù¥…Ñ”€ôÕÍ•9…Ù¥…Ñ” ¤ì(€½¹ÍĞm™½É´°Í•Ñ½Éµt€ôÕÍ•MÑ…Ñ”¡ìÕÍ•É¹…µ”è€œœ°Á…ÍÍİ½Éè€œœô¤ì(€½¹ÍĞmÍ¡½İA…ÍÌ°Í•ÑM¡½İA…ÍÍt€ôÕÍ•MÑ…Ñ”¡™…±Í”¤ì(€½¹ÍĞm±½…‘¥¹œ°Í•Ñ1½…‘¥¹t€ôÕÍ•MÑ…Ñ”¡™…±Í”¤ì((€½¹ÍĞ¡…¹‘±•MÕ‰µ¥Ğ€ô…Íå¹Œ€¡•Ù•¹Ğ¤€ôøì(€€€•Ù•¹Ğ¹ÁÉ•Ù•¹Ñ•™…Õ±Ğ ¤ì(€€€¥˜€ …™½É´¹ÕÍ•É¹…µ”ñğ€…™½É´¹Á…ÍÍİ½É¤ì(€€€€€Ñ½…ÍĞ¹•ÉÉ½È UÍ•É¹…µ”‘…¸Á…ÍÍİ½Éİ…©¥ˆ‘¥¥Í¤œ¤ì(€€€€€É•ÑÕÉ¸ì(€€€ô(€€€Í•Ñ1½…‘¥¹œ¡ÑÉÕ”¤ì(€€€ÑÉäì(€€€€€½¹ÍĞÕÍ•È€ô…İ…¥Ğ±½¥¸¡™½É´¹ÕÍ•É¹…µ”°™½É´¹Á…ÍÍİ½É¤ì(€€€€€Ñ½…ÍĞ¹ÍÕ•ÍÌ¡M•±…µ…Ğ‘…Ñ…¹œ°€‘íÕÍ•È¹ÕÍ•É¹…µ•ô…€¤ì(€€€€€¹…Ù¥…Ñ”¡•Ñ!½µ•A…Ñ ¡ÕÍ•È¹É½±”¤¤ì(€€€ô…Ñ €¡•ÉÉ½È¤ì(€€€€€Ñ½…ÍĞ¹•ÉÉ½È¡•ÉÉ½È¹É•ÍÁ½¹Í”ü¹‘…Ñ„ü¹•ÉÉ½Èñğ€UÍ•É¹…µ”…Ñ…ÔÁ…ÍÍİ½ÉÍ…±… œ¤ì(€€€ô™¥¹…±±äì(€€€€€Í•Ñ1½…‘¥¹œ¡™…±Í”¤ì(€€€ô(€ôì((€É•ÑÕÉ¸€ (€€€€ñµ…¥¸±…ÍÍ9…µ”ô‰É…Á¥Á½Ìµ±½¥¸ˆø(€€€€€€ñÍ•Ñ¥½¸±…ÍÍ9…µ”ô‰É…Á¥Á½Ìµ±½¥¹}n4æÚ$z{-®éÜj×__field svg { position:absolute; top:13px; left:14px; color:var(--outline); pointer-events:none; }
        .rapipos-login__field .input { padding-left:42px; min-height:46px; }
        .rapipos-login__field button { position:absolute; right:10px; top:8px; display:grid; place-items:center; width:30px; height:30px; border:0; border-radius:8px; background:transparent; color:var(--outline); cursor:pointer; }
        .rapipos-login__field button svg { position:static; }
        .rapipos-login__submit { margin-top:28px; border-radius:12px; }
        .rapipos-login__hint { display:flex; align-items:flex-start; gap:9px; margin-top:20px; padding:12px; border:1px dashed var(--outline-variant); border-radius:12px; background:var(--surface-container-low); color:var(--on-surface-variant); font-size:11px; line-height:1.5; }
        .rapipos-login__hint svg { flex:0 0 auto; margin-top:1px; color:var(--primary); }
        .rapipos-login__hint strong { color:var(--primary); }
        .rapipos-login__hint code { font-size:10px; overflow-wrap:anywhere; }
        @media (max-width:820px) { .rapipos-login { grid-template-columns:1fr; } .rapipos-login__brand { display:none; } .rapipos-login__panel { min-height:100dvh; padding:84px 22px 36px; } .rapipos-login__mobile-brand { display:flex; margin-bottom:34px; } .rapipos-login__toolbar { top:20px; right:18px; } }
        @media (max-width:420px) { .rapipos-login__panel { padding-left:18px; padding-right:18px; } }
      `}</style>
    </main>
  );
}
