import { useCallback, useEffect, useState } from 'react';
import toast from 'react-hot-toast';
import api, { formatDate, formatRupiah } from '../utils/api';
import Icon from '../components/Icon';

const STATUS={received:'Diterima',diagnosis:'Diagnosis',awaiting_approval:'Menunggu Persetujuan',awaiting_parts:'Menunggu Sparepart',in_progress:'Dikerjakan',ready:'Siap Diambil',completed:'Selesai',cancelled:'Dibatalkan'};
const empty={customer_id:'',service_product_id:'',item_name:'',item_brand:'',item_serial:'',complaint:'',estimated_cost:'',deposit_amount:'',deposit_payment_method:'cash',due_at:'',notes:''};
const methods=['cash','qris','transfer','gopay','ovo','dana','linkaja','shopeepay'];

export default function ServiceOrders(){
 const [orders,setOrders]=useState([]),[customers,setCustomers]=useState([]),[products,setProducts]=useState([]),[services,setServices]=useState([]),[form,setForm]=useState(empty),[show,setShow]=useState(false),[active,setActive]=useState(null),[status,setStatus]=useState(''),[loading,setLoading]=useState(true);
 const load=useCallback(async()=>{setLoading(true);try{const [o,c,p]=await Promise.all([api.get('/service-orders',{params:{status}}),api.get('/customers',{params:{limit:200}}),api.get('/products',{params:{limit:300}})]);setOrders(o.data.data||[]);setCustomers(c.data.data||[]);const all=p.data.data||[];setProducts(all.filter(x=>x.item_type==='physical'));setServices(all.filter(x=>x.item_type==='service'))}catch{toast.error('Gagal memuat data servis')}finally{setLoading(false)}},[status]);
 useEffect(()=>{load()},[load]);
 const refresh=async id=>{const r=await api.get(`/service-orders/${id}`);setActive(r.data.data);load()};
 const create=async()=>{if(!form.customer_id||!form.service_product_id||!form.item_name)return toast.error('Pelanggan, layanan, dan barang wajib dipilih');try{await api.post('/service-orders',{...form,customer_id:+form.customer_id,service_product_id:+form.service_product_id,estimated_cost:+form.estimated_cost||0,deposit_amount:+form.deposit_amount||0,due_at:form.due_at?new Date(form.due_at).toISOString():''});toast.success('Order servis dibuat');setForm(empty);setShow(false);load()}catch(e){toast.error(e.response?.data?.error||'Gagal membuat order')}};
 const statusUpdate=async s=>{const note=prompt(`Catatan ${STATUS[s]} (opsional):`)??'';try{await api.post(`/service-orders/${active.id}/status`,{status:s,note});toast.success('Progres diperbarui');refresh(active.id)}catch(e){toast.error(e.response?.data?.error||'Gagal update progres')}};
 const part=async()=>{const product_id=+(prompt('ID sparepart:')||0),quantity=+(prompt('Jumlah:','1')||0);if(!product_id||!quantity)return;try{await api.post(`/service-orders/${active.id}/parts`,{product_id,quantity});toast.success('Sparepart ditambahkan');refresh(active.id)}catch(e){toast.error(e.response?.data?.error||'Gagal menambah sparepart')}};
 const deposit=async()=>{const amount=+(prompt('Nominal DP tambahan:')||0),payment_method=prompt('Metode pembayaran:', 'cash');if(!amount||!payment_method)return;try{await api.post(`/service-orders/${active.id}/deposit`,{amount,payment_method});toast.success('DP tercatat');refresh(active.id)}catch(e){toast.error(e.response?.data?.error||'Gagal mencatat DP')}};
 const cost=async()=>{const cost_type=prompt('Jenis biaya: labor, external, other','labor'),amount=+(prompt('Nominal biaya:')||0);if(!cost_type||!amount)return;const description=prompt('Keterangan:')||'';try{await api.post(`/service-orders/${active.id}/costs`,{cost_type,amount,description});toast.success('Biaya pekerjaan tercatat');refresh(active.id)}catch(e){toast.error(e.response?.data?.error||'Gagal mencatat biaya')}};
 const reserve=async()=>{try{await api.post(`/service-orders/${active.id}/reserve`);toast.success('Sparepart direservasi');refresh(active.id)}catch(e){toast.error(e.response?.data?.error||'Reservasi gagal')}};
 const checkout=async()=>{const payment_method=prompt('Metode bayar sisa tagihan:', 'cash');if(!payment_method)return;const payment_amount=payment_method==='cash'?+(prompt('Tunai diterima:')||0):0;try{const r=await api.post('/checkout',{service_order_id:active.id,payment_method,payment_amount});toast.success(`Invoice ${r.data.data.invoice_number} dibuat`);setActive(null);load()}catch(e){toast.error(e.response?.data?.error||'Gagal finalkan invoice')}};
 return <div style={{padding:24}}><div className="page-header"><div><h1 className="page-title font-headline">Order Servis</h1><p className="page-subtitle">DP, biaya kerja, sparepart, dan invoice jasa.</p></div><button className="btn btn-primary" onClick={()=>setShow(true)}><Icon name="add" size={16}/>Order Baru</button></div>
 <div className="card" style={{padding:14,marginBottom:16}}><select className="input" style={{maxWidth:260}} value={status} onChange={e=>setStatus(e.target.value)}><option value="">Semua status</option>{Object.entries(STATUS).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></div>
 <div className="card" style={{padding:0,overflow:'hidden'}}><div className="table-wrap"><table><thead><tr><th>Order</th><th>Pelanggan / Barang</th><th>Status</th><th>Estimasi</th><th>DP</th><th/></tr></thead><tbody>{loading?<tr><td colSpan="6" style={{padding:32,textAlign:'center'}}>Memuat…</td></tr>:orders.length===0?<tr><td colSpan="6" style={{padding:32,textAlign:'center'}}>Belum ada order servis.</td></tr>:orders.map(o=><tr key={o.id}><td className="mono">{o.order_number}</td><td><b>{o.customer_name}</b><br/><small>{o.item_name} {o.item_brand&&`· ${o.item_brand}`}</small></td><td><span className="badge badge-teal">{STATUS[o.status]}</span></td><td>{formatRupiah(o.estimated_cost)}</td><td>{formatRupiah(o.deposit_balance??o.deposit_amount)}</td><td><button className="btn btn-ghost" onClick={()=>refresh(o.id)}>Kelola</button></td></tr>)}</tbody></table></div></div>
 {show&&<div className="modal-backdrop"><div className="modal" style={{maxWidth:720}}><div className="modal-header"><h2>Order Servis Baru</h2><button className="icon-btn" onClick={()=>setShow(false)}><Icon name="close"/></button></div><div className="modal-body" style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:12}}><label>Pelanggan<select className="input" value={form.customer_id} onChange={e=>setForm({...form,customer_id:e.target.value})}><option value="">Pilih pelanggan</option>{customers.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>Layanan<select className="input" value={form.service_product_id} onChange={e=>setForm({...form,service_product_id:e.target.value})}><option value="">Pilih layanan</option>{services.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label>{[['item_name','Barang yang diservis'],['item_brand','Merek/model'],['item_serial','Serial/IMEI'],['estimated_cost','Estimasi biaya']].map(([k,l])=><label key={k}>{l}<input className="input" type={k==='estimated_cost'?'number':'text'} value={form[k]} onChange={e=>setForm({...form,[k]:e.target.value})}/></label>)}<label>DP diterima<input className="input" type="number" value={form.deposit_amount} onChange={e=>setForm({...form,deposit_amount:e.target.value})}/></label><label>Metode DP<select className="input" value={form.deposit_payment_method} onChange={e=>setForm({...form,deposit_payment_method:e.target.value})}>{methods.map(x=><option key={x}>{x.toUpperCase()}</option>)}</select></label><label>Target selesai<input className="input" type="datetime-local" value={form.due_at} onChange={e=>setForm({...form,due_at:e.target.value})}/></label><label style={{gridColumn:'1/-1'}}>Keluhan<textarea className="input" rows="2" value={form.complaint} onChange={e=>setForm({...form,complaint:e.target.value})}/></label></div><div className="modal-footer"><button className="btn btn-ghost" onClick={()=>setShow(false)}>Batal</button><button className="btn btn-primary" onClick={create}>Buat order</button></div></div></div>}
 {active&&<div className="modal-backdrop"><div className="modal" style={{maxWidth:760}}><div className="modal-header"><div><h2>{active.order_number}</h2><small>{active.customer_name} · {active.item_name}</small></div><button className="icon-btn" onClick={()=>setActive(null)}><Icon name="close"/></button></div><div className="modal-body"><p><b>Status:</b> {STATUS[active.status]} · <b>Estimasi:</b> {formatRupiah(active.estimated_cost)} · <b>DP:</b> {formatRupiah(active.deposit_balance??active.deposit_amount)} · <b>Sisa:</b> {formatRupiah(active.outstanding_amount||0)}</p><div style={{display:'flex',gap:6,flexWrap:'wrap'}}>{Object.entries(STATUS).filter(([k])=>!['completed','cancelled'].includes(k)).map(([k,v])=><button key={k} className="btn btn-ghost" onClick={()=>statusUpdate(k)}>{v}</button>)}</div><hr/><h3>Sparepart</h3>{active.parts?.length?<ul>{active.parts.map(x=><li key={x.id}>{x.product_name} × {x.quantity} — {formatRupiah(x.subtotal)} {x.reserved_quantity>0&&'(reserved)'}</li>)}</ul>:<p>Belum ada sparepart.</p>}<div style={{display:'flex',gap:6,flexWrap:'wrap'}}><button className="btn btn-ghost" onClick={part}>+ Sparepart</button><button className="btn btn-ghost" onClick={reserve}>Reservasi</button><button className="btn btn-ghost" onClick={deposit}>+ DP</button><button className="btn btn-ghost" onClick={cost}>+ Biaya kerja</button></div><p style={{fontSize:12}}>ID produk fisik: {products.map(p=>`${p.id}=${p.name}`).join(' · ')}</p><h3>Biaya pekerjaan</h3>{active.costs?.length?<ul>{active.costs.map(x=><li key={x.id}>{x.cost_type}: {x.description||'Tanpa keterangan'} — {formatRupiah(x.amount)}</li>)}</ul>:<p>Belum ada biaya langsung.</p>}<hr/><h3>Riwayat progres</h3>{active.progress?.map(x=><p key={x.id}><b>{STATUS[x.status]||x.status}</b> — {x.note||'Tanpa catatan'} <small>({x.actor_name}, {formatDate(x.created_at)})</small></p>)}{!active.invoice_number?<button className="btn btn-primary" onClick={checkout}><Icon name="receipt_long" size={16}/>Finalkan & Buat Invoice</button>:<p className="badge badge-green">Invoice {active.invoice_number}</p>}</div></div></div>}</div>
}
