import { useCallback, useEffect, useState } from 'react';
import toast from 'react-hot-toast';
import api, { formatDate, formatRupiah } from '../utils/api';
import Icon from '../components/Icon';

const STATUS = { received:'Diterima', diagnosis:'Diagnosis', awaiting_approval:'Menunggu Persetujuan', awaiting_parts:'Menunggu Sparepart', in_progress:'Dikerjakan', ready:'Siap Diambil', completed:'Selesai', cancelled:'Dibatalkan' };
const empty = { customer_id:'', service_product_id:'', item_name:'', item_brand:'', item_serial:'', complaint:'', estimated_cost:'', deposit_amount:'', due_at:'', notes:'' };

export default function ServiceOrders() {
  const [orders,setOrders]=useState([]), [customers,setCustomers]=useState([]), [products,setProducts]=useState([]), [services,setServices]=useState([]);
  const [show,setShow]=useState(false), [form,setForm]=useState(empty), [active,setActive]=useState(null), [loading,setLoading]=useState(true), [status,setStatus]=useState('');
  const load=useCallback(async()=>{setLoading(true);try{const [o,c,p]=await Promise.all([api.get('/service-orders',{params:{status}}),api.get('/customers',{params:{limit:200}}),api.get('/products',{params:{limit:300}})]);setOrders(o.data.data||[]);setCustomers(c.data.data||[]);const items=p.data.data||[];setProducts(items.filter(x=>x.item_type!=='service'));setServices(items.filter(x=>x.item_type==='service'));}catch{toast.error('Gagal memuat data servis')}finally{setLoading(false)}},[status]);
  useEffect(()=>{load()},[load]);
  const create=async()=>{if(!form.customer_id||!form.service_product_id||!form.item_name){toast.error('Pelanggan, layanan, dan barang wajib dipilih');return}try{await api.post('/service-orders',{...form,customer_id:+form.customer_id,service_product_id:+form.service_product_id,estimated_cost:+form.estimated_cost||0,deposit_amount:+form.deposit_amount||0,due_at:form.due_at?new Date(form.due_at).toISOString():''});toast.success('Order servis dibuat');setShow(false);setForm(empty);load()}catch(e){toast.error(e.response?.data?.error||'Gagal membuat order')}};
  const updateStatus=async(o,newStatus)=>{const note=prompt(`Catatan untuk status ${STATUS[newStatus]} (opsional):`)??'';try{await api.post(`/service-orders/${o.id}/status`,{status:newStatus,note});toast.success('Progress diperbarui');setActive(null);load()}catch(e){toast.error(e.response?.data?.error||'Gagal update progress')}};
  const addPart=async(o)=>{const id=prompt('ID sparepart (lihat daftar produk fisik di bawah):');if(!id)return;const qty=prompt('Jumlah:','1');if(!qty)return;try{await api.post(`/service-orders/${o.id}/parts`,{product_id:+id,quantity:+qty});toast.success('Sparepart ditambahkan ke estimasi');const x=await api.get(`/service-orders/${o.id}`);setActive(x.data.data);load()}catch(e){toast.error(e.response?.data?.error||'Gagal tambah sparepart')}};
  const checkout=async(o)=>{if(!confirm(`Finalkan ${o.order_number}? Stok sparepart akan dipotong dan invoice dibuat.`))return;const payment_method=prompt('Metode bayar: cash, qris, atau e-wallet (gopay/ovo/dana/linkaja/shopeepay)','cash');if(!payment_method)return;let payment_amount=0;if(payment_method==='cash'){payment_amount=+(prompt('Nominal tunai diterima:')||0)}try{const r=await api.post('/checkout',{service_order_id:o.id,payment_method,payment_amount});toast.success(`Invoice ${r.data.data.invoice_number} dibuat`);setActive(null);load()}catch(e){toast.error(e.response?.data?.error||'Gagal finalkan invoice')}};
  const copy=(text)=>navigator.clipboard?.writeText(text).then(()=>toast.success('Disalin'));
  return <div style={{padding:24}}>
    <div className="page-header"><div><h1 className="page-title font-headline">Order Servis</h1><p className="page-subtitle">Terima, kerjakan, dan tagihkan jasa beserta sparepart.</p></div><button className="btn btn-primary" onClick={()=>setShow(true)}><Icon name="add" size={16}/> Order Baru</button></div>
    <div className="card" style={{padding:14,marginBottom:16,display:'flex',gap:8,alignItems:'center'}}><select className="input" style={{maxWidth:260}} value={status} onChange={e=>setStatus(e.target.value)}><option value="">Semua status</option>{Object.entries(STATUS).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select><button className="btn btn-ghost" onClick={load}><Icon name="refresh" size={16}/></button></div>
    <div className="card" style={{padding:0,overflow:'hidden'}}><div className="table-wrap"><table><thead><tr><th>Order</th><th>Pelanggan / Barang</th><th>Layanan</th><th>Teknisi</th><th>Status</th><th>Estimasi</th><th>Diperbarui</th><th/></tr></thead><tbody>{loading?<tr><td colSpan="8" style={{padding:32,textAlign:'center'}}><div className="spinner" style={{margin:'auto'}}/></td></tr>:orders.length===0?<tr><td colSpan="8" style={{padding:32,textAlign:'center'}}>Belum ada order servis.</td></tr>:orders.map(o=><tr key={o.id}><td className="mono" style={{fontWeight:700}}>{o.order_number}</td><td><b>{o.customer_name}</b><br/><span style={{fontSize:12}}>{o.item_name} {o.item_brand&&`· ${o.item_brand}`}</span></td><td>{services.find(x=>x.id===o.service_product_id)?.name||'—'}</td><td>{o.technician_name||'Belum ditugaskan'}</td><td><span className="badge badge-teal">{STATUS[o.status]}</span></td><td>{formatRupiah(o.estimated_cost)}</td><td style={{fontSize:12}}>{formatDate(o.updated_at)}</td><td><button className="btn btn-ghost" onClick={()=>setActive(o)}>Kelola</button></td></tr>)}</tbody></table></div></div>
    {show&&<div className="modal-backdrop"><div className="modal" style={{maxWidth:720}}><div className="modal-header"><h2>Order Servis Baru</h2><button className="icon-btn" onClick={()=>setShow(false)}><Icon name="close"/></button></div><div className="modal-body" style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:12}}>{[['customer_id','Pelanggan'],['service_product_id','Jenis layanan']].map(([k,l])=><label key={k}>{l}<select className="input" value={form[k]} onChange={e=>setForm({...form,[k]:e.target.value})}><option value="">Pilih {l}</option>{(k==='customer_id'?customers:services).map(x=><option key={x.id} value={x.id}>{x.name}{x.phone?` · ${x.phone}`:''}</option>)}</select></label>)}<label>Barang yang diservis<input className="input" value={form.item_name} onChange={e=>setForm({...form,item_name:e.target.value})}/></label><label>Merek / Model<input className="input" value={form.item_brand} onChange={e=>setForm({...form,item_brand:e.target.value})}/></label><label>Serial / IMEI<input className="input" value={form.item_serial} onChange={e=>setForm({...form,item_serial:e.target.value})}/></label><label>Target selesai<input type="datetime-local" className="input" value={form.due_at} onChange={e=>setForm({...form,due_at:e.target.value})}/></label><label>Estimasi biaya<input type="number" className="input" value={form.estimated_cost} onChange={e=>setForm({...form,estimated_cost:e.target.value})}/></label><label>DP diterima<input type="number" className="input" value={form.deposit_amount} onChange={e=>setForm({...form,deposit_amount:e.target.value})}/></label><label style={{gridColumn:'1/-1'}}>Keluhan<textarea className="input" rows="3" value={form.complaint} onChange={e=>setForm({...form,complaint:e.target.value})}/></label><label style={{gridColumn:'1/-1'}}>Catatan internal<textarea className="input" rows="2" value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></label></div><div className="modal-footer"><button className="btn btn-ghost" onClick={()=>setShow(false)}>Batal</button><button className="btn btn-primary" onClick={create}>Buat order</button></div></div></div>}
    {active&&<div className="modal-backdrop"><div className="modal" style={{maxWidth:760}}><div className="modal-header"><div><h2>{active.order_number}</h2><small>{active.customer_name} · {active.item_name}</small></div><button className="icon-btn" onClick={()=>setActive(null)}><Icon name="close"/></button></div><div className="modal-body"><p><b>Status:</b> {STATUS[active.status]} &nbsp; <b>Estimasi:</b> {formatRupiah(active.estimated_cost)} &nbsp; <b>DP:</b> {formatRupiah(active.deposit_amount)}</p><p style={{fontSize:13}}><b>Token tracking:</b> <code>{active.tracking_token}</code> <button className="btn btn-ghost" onClick={()=>copy(active.tracking_token)}>Salin</button></p><div style={{display:'flex',gap:6,flexWrap:'wrap',margin:'14px 0'}}>{Object.entries(STATUS).filter(([k])=>!['completed','cancelled'].includes(k)).map(([k,v])=><button key={k} className="btn btn-ghost" onClick={()=>updateStatus(active,k)} disabled={active.status==='completed'}>{v}</button>)}</div><hr/><h3>Sparepart estimasi</h3>{active.parts?.length?<ul>{active.parts.map(x=><li key={x.id}>{x.product_name} × {x.quantity} — {formatRupiah(x.subtotal)}</li>)}</ul>:<p>Belum ada sparepart.</p>}<button className="btn btn-ghost" onClick={()=>addPart(active)} disabled={active.invoice_number}>+ Tambah sparepart</button><p style={{fontSize:12,marginTop:8}}>ID produk fisik: {products.map(p=>`${p.id}=${p.name}`).join(' · ')||'Tidak ada'}</p><hr/><h3>Riwayat progres</h3>{active.progress?.map(x=><p key={x.id} style={{fontSize:13}}><b>{STATUS[x.status]||x.status}</b> — {x.note||'Tanpa catatan'} <span style={{color:'var(--outline)'}}>({x.actor_name}, {formatDate(x.created_at)})</span></p>)}{!active.invoice_number&&<button className="btn btn-primary" style={{marginTop:12}} onClick={()=>checkout(active)}><Icon name="receipt_long" size={16}/> Finalkan & Buat Invoice</button>}{active.invoice_number&&<p className="badge badge-green">Invoice {active.invoice_number}</p>}</div></div></div>}
  </div>;
}
