package handlers

import (
	"database/sql"
	"encoding/json"
	"net/http"
	"strconv"
	"time"

	"kasir-umkm/internal/database"
	"kasir-umkm/internal/middleware"
	"kasir-umkm/internal/models"
	"github.com/gorilla/mux"
)

type expenseRequest struct { Date, Category, Description, PaymentMethod string; Amount float64 }
type settlementRequest struct { Date, PaymentMethod, BankReference, Note string; GrossAmount, FeeAmount, NetAmount float64 }
type closePeriodRequest struct { PeriodKey, Note string }
type refundRequest struct { PaymentLedgerID int64 `json:"payment_ledger_id"`; Amount float64 `json:"amount"`; Reason string `json:"reason"` }
type opnameRequest struct { Name string `json:"name"`; Items []opnameItem `json:"items"` }
type opnameItem struct { ProductID int64 `json:"product_id"`; CountedQuantity int `json:"counted_quantity"`; Note string `json:"note"` }

func isPeriodOpen(tx *sql.Tx, at time.Time) bool { var status string; err:=tx.QueryRow("SELECT status FROM accounting_periods WHERE period_key=?",at.Format("2006-01")).Scan(&status); return err==sql.ErrNoRows||status=="open" }

func CreateExpense(w http.ResponseWriter,r *http.Request){ claims:=middleware.GetClaims(r);var req expenseRequest;if json.NewDecoder(r.Body).Decode(&req)!=nil||req.Amount<=0||req.Category==""||!validPaymentMethod(req.PaymentMethod){writeJSON(w,400,models.APIResponse{Success:false,Error:"Data pengeluaran tidak valid"});return};at:=time.Now();if req.Date!=""{if d,e:=time.Parse("2006-01-02",req.Date);e==nil{at=d}else{writeJSON(w,400,models.APIResponse{Success:false,Error:"Tanggal tidak valid"});return}};tx,e:=database.DB.Begin();if e!=nil||!isPeriodOpen(tx,at){if tx!=nil{tx.Rollback()};writeJSON(w,409,models.APIResponse{Success:false,Error:"Periode akuntansi sudah ditutup"});return};defer tx.Rollback();res,e:=tx.Exec("INSERT INTO business_expenses(expense_date,category,description,amount,payment_method,created_by) VALUES(?,?,?,?,?,?)",at.Format("2006-01-02"),req.Category,req.Description,req.Amount,req.PaymentMethod,claims.UserID);if e!=nil{writeJSON(w,500,models.APIResponse{Success:false,Error:"Gagal menyimpan pengeluaran"});return};id,_:=res.LastInsertId();if req.PaymentMethod=="cash"{if _,e=postPayment(tx,0,0,0,"refund","out","cash",req.Amount,"Pengeluaran #"+strconv.FormatInt(id,10)+": "+req.Category,claims.UserID,time.Now());e!=nil{writeJSON(w,500,models.APIResponse{Success:false,Error:"Gagal mencatat arus kas"});return}};if e=tx.Commit();e!=nil{writeJSON(w,500,models.APIResponse{Success:false,Error:"Gagal menyimpan pengeluaran"});return};writeJSON(w,201,models.APIResponse{Success:true,Message:"Pengeluaran dicatat",Data:map[string]interface{}{"id":id}})}

func GetExpenses(w http.ResponseWriter,r *http.Request){rows,e:=database.DB.Query("SELECT id,expense_date,category,description,amount,payment_method,status,void_reason,created_at FROM business_expenses ORDER BY expense_date DESC,id DESC LIMIT 200");if e!=nil{writeJSON(w,500,models.APIResponse{Success:false,Error:"Gagal membaca pengeluaran"});return};defer rows.Close();out:=[]map[string]interface{}{};for rows.Next(){var id int64;var date,cat,desc,method,status,reason,created string;var amount float64;rows.Scan(&id,&date,&cat,&desc,&amount,&method,&status,&reason,&created);out=append(out,map[string]interface{}{"id":id,"date":date,"category":cat,"description":desc,"amount":amount,"payment_method":method,"status":status,"void_reason":reason,"created_at":created})};writeJSON(w,200,models.APIResponse{Success:true,Data:out})}

func RecordSettlement(w http.ResponseWriter,r *http.Request){claims:=middleware.GetClaims(r);var req settlementRequest;if json.NewDecoder(r.Body).Decode(&req)!=nil||req.Date==""||req.PaymentMethod=="cash"||req.GrossAmount<0||req.FeeAmount<0||req.NetAmount<0{writeJSON(w,400,models.APIResponse{Success:false,Error:"Data settlement tidak valid"});return};status:="matched";if req.GrossAmount-req.FeeAmount!=req.NetAmount{status="difference"};_,e:=database.DB.Exec("INSERT INTO payment_settlements(settlement_date,payment_method,gross_amount,fee_amount,net_amount,bank_reference,status,note,created_by) VALUES(?,?,?,?,?,?,?,?,?)",req.Date,req.PaymentMethod,req.GrossAmount,req.FeeAmount,req.NetAmount,req.BankReference,status,req.Note,claims.UserID);if e!=nil{writeJSON(w,500,models.APIResponse{Success:false,Error:"Gagal mencatat settlement"});return};writeJSON(w,201,models.APIResponse{Success:true,Message:"Settlement dicatat",Data:map[string]string{"status":status}})}

func CloseAccountingPeriod(w http.ResponseWriter,r *http.Request){claims:=middleware.GetClaims(r);var req closePeriodRequest;if json.NewDecoder(r.Body).Decode(&req)!=nil||len(req.PeriodKey)!=7{writeJSON(w,400,models.APIResponse{Success:false,Error:"Periode gunakan format YYYY-MM"});return};_,e:=database.DB.Exec("INSERT INTO accounting_periods(period_key,status,closed_by,closed_at,note) VALUES(?,'closed',?,?,?) ON CONFLICT(period_key) DO UPDATE SET status='closed',closed_by=excluded.closed_by,closed_at=excluded.closed_at,note=excluded.note",req.PeriodKey,claims.UserID,time.Now(),req.Note);if e!=nil{writeJSON(w,500,models.APIResponse{Success:false,Error:"Gagal menutup periode"});return};writeJSON(w,200,models.APIResponse{Success:true,Message:"Periode ditutup. Transaksi baru pada periode ini diblokir."})}

func ReversePayment(w http.ResponseWriter,r *http.Request){claims:=middleware.GetClaims(r);var req refundRequest;if json.NewDecoder(r.Body).Decode(&req)!=nil||req.PaymentLedgerID<=0||req.Amount<=0||req.Reason==""{writeJSON(w,400,models.APIResponse{Success:false,Error:"Bukti bayar, nominal, dan alasan refund wajib diisi"});return};tx,e:=database.DB.Begin();if e!=nil{writeJSON(w,500,models.APIResponse{Success:false,Error:"Gagal memulai refund"});return};defer tx.Rollback();var tid,sid,cid sql.NullInt64;var method string;var paid float64;if e=tx.QueryRow("SELECT transaction_id,service_order_id,customer_id,payment_method,amount FROM payment_ledger WHERE id=? AND direction='in'",req.PaymentLedgerID).Scan(&tid,&sid,&cid,&method,&paid);e!=nil||req.Amount>paid{writeJSON(w,400,models.APIResponse{Success:false,Error:"Pembayaran tidak dapat direfund"});return};var already float64;tx.QueryRow("SELECT COALESCE(SUM(amount),0) FROM payment_ledger WHERE reversal_of=?",req.PaymentLedgerID).Scan(&already);if already+req.Amount>paid{writeJSON(w,409,models.APIResponse{Success:false,Error:"Nominal melebihi sisa pembayaran"});return};receipt,e:=postPayment(tx,tid.Int64,sid.Int64,cid.Int64,"refund","out",method,req.Amount,req.Reason,claims.UserID,time.Now());if e!=nil{writeJSON(w,500,models.APIResponse{Success:false,Error:"Gagal merekam refund"});return};_,e=tx.Exec("UPDATE payment_ledger SET reversal_of=? WHERE receipt_number=?",req.PaymentLedgerID,receipt);if e!=nil{writeJSON(w,500,models.APIResponse{Success:false,Error:"Gagal mengaitkan refund"});return};if e=tx.Commit();e!=nil{writeJSON(w,500,models.APIResponse{Success:false,Error:"Gagal menyimpan refund"});return};writeJSON(w,201,models.APIResponse{Success:true,Message:"Refund dicatat sebagai pembalikan ledger",Data:map[string]string{"receipt_number":receipt}})}

func CreateStockOpname(w http.ResponseWriter,r *http.Request){claims:=middleware.GetClaims(r);var req opnameRequest;if json.NewDecoder(r.Body).Decode(&req)!=nil||req.Name==""||len(req.Items)==0{writeJSON(w,400,models.APIResponse{Success:false,Error:"Nama dan item opname wajib diisi"});return};tx,e:=database.DB.Begin();if e!=nil{writeJSON(w,500,models.APIResponse{Success:false,Error:"Gagal membuat opname"});return};defer tx.Rollback();res,e:=tx.Exec("INSERT INTO stock_opname_sessions(name,created_by) VALUES(?,?)",req.Name,claims.UserID);if e!=nil{writeJSON(w,500,models.APIResponse{Success:false,Error:"Gagal membuat sesi opname"});return};id,_:=res.LastInsertId();for _,it:=range req.Items{var stock int;if e=tx.QueryRow("SELECT stock FROM products WHERE id=? AND item_type='physical' AND is_deleted=0",it.ProductID).Scan(&stock);e!=nil{writeJSON(w,400,models.APIResponse{Success:false,Error:"Produk opname tidak valid"});return};tx.Exec("INSERT INTO stock_opname_items(session_id,product_id,system_quantity,counted_quantity,note) VALUES(?,?,?,?,?)",id,it.ProductID,stock,it.CountedQuantity,it.Note)};tx.Commit();writeJSON(w,201,models.APIResponse{Success:true,Data:map[string]interface{}{"id":id}})}

func PostStockOpname(w http.ResponseWriter,r *http.Request){claims:=middleware.GetClaims(r);id,_:=strconv.ParseInt(mux.Vars(r)["id"],10,64);tx,e:=database.DB.Begin();if e!=nil{writeJSON(w,500,models.APIResponse{Success:false,Error:"Gagal posting opname"});return};defer tx.Rollback();var status string;if tx.QueryRow("SELECT status FROM stock_opname_sessions WHERE id=?",id).Scan(&status)!=nil||status!="draft"{writeJSON(w,409,models.APIResponse{Success:false,Error:"Sesi opname tidak dapat diposting"});return};rows,e:=tx.Query("SELECT product_id,system_quantity,counted_quantity,note FROM stock_opname_items WHERE session_id=?",id);if e!=nil{writeJSON(w,500,models.APIResponse{Success:false,Error:"Gagal membaca item opname"});return};defer rows.Close();now:=time.Now();for rows.Next(){var productID int64;var system,counted int;var note string;rows.Scan(&productID,&system,&counted,&note);diff:=counted-system;if diff!=0{tx.Exec("UPDATE products SET stock=?,updated_at=?,updated_by=?,version=version+1 WHERE id=?",counted,now,claims.UserID,productID);tx.Exec("INSERT INTO stock_mutations(product_id,type,quantity,stock_before,stock_after,note,ref_id,user_id,created_at) VALUES(?,?,?,?,?,?,?,?,?)",productID,"opname",diff,system,counted,"Opname #"+strconv.FormatInt(id,10)+": "+note,id,claims.UserID,now)}};tx.Exec("UPDATE stock_opname_sessions SET status='posted',posted_by=?,posted_at=? WHERE id=?",claims.UserID,now,id);tx.Commit();writeJSON(w,200,models.APIResponse{Success:true,Message:"Opname diposting dan stok disesuaikan"})}
